apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../0-flux-repo-conf/
  - ../0-k8s-common/
  - ../0-k8s-on-premise/
  - ../0-k8s-namespaces/
resources:
  - cluster.yaml
  - resources/cert-cluster-issuer.yaml
  - resources/harbor.yaml
  - resources/nexus.yaml
  - resources/pgadmin4.yaml
  - resources/bitwarden.yaml
patchesStrategicMerge: []
