---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    app: metallb
---
# See: https://metallb.universe.tf/concepts
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
  annotations:
    flux.weave.works/locked: "true"
spec:
  interval: 5m
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: bitname
        namespace: flux-system
      version: 2.3.0
  values:
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          # addresses:
          #   - 10.x.x.x-10.x.x.x

    prometheus:
      enabled: true

      serviceMonitor:
        enabled: true
