---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: filebeat
  namespace: logging-system
  annotations:
    flux.weave.works/locked: "true"
spec:
  interval: 5m
  releaseName: filebeat
  chart:
    spec:
      chart: filebeat
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      version: 7.12.0
  values:
    filebeatConfig:
      filebeat.yml: |
        filebeat.inputs:
        - type: container
          paths:
            - /var/log/containers/*.log
          processors:
          - add_kubernetes_metadata:
              host: ${NODE_NAME}
              matchers:
              - logs_path:
                  logs_path: "/var/log/containers/"

        processors:
          - add_cloud_metadata: ~
          - add_host_metadata: ~

        output.logstash:
          hosts: ["logstash-logstash:5044"]

        logging.level: warning
