apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: devops@test.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - selector:
          dnsZones:
            - "test.com"
        dns01:
          route53:
            region: us-east-1
            hostedZoneID: "ZXXXXXXXXXXXXXXXXXXXX"
            accessKeyID: "AKIAXXXXXXXXXXXXXXXX"
            secretAccessKeySecretRef:
              name: route53-credentials-secret
              key: secret-access-key
