---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: pgadmin4
  name: pgadmin4
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin4
  namespace: pgadmin4
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 5m
  releaseName: pgadmin4
  chart:
    spec:
      chart: "pgadmin4"
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: flux-system
      version: 1.5.0
  values:
    env:
      variables:
      - name: PGADMIN_LISTEN_ADDRESS
        value: "0.0.0.0"
      - name: PGADMIN_LISTEN_PORT
        value: "80"
    persistentVolume:
      enabled: true
      size: "10Gi"