apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: git-repository
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@git.test.com/devops/kubernetes/deployments-devops.git
  ref:
    branch: master
  secretRef:
    name: flux-git-deploy